name: smartavia_weather
description: Smartavia Simple Weather App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.6.1
  hive: ^2.2.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_svg: ^2.0.3
  geolocator: ^9.0.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  hive_generator: ^2.0.0
  json_annotation: ^4.8.0
  dio: ^5.0.2
  flutter_secure_storage: ^8.0.0
  hive_flutter: ^1.1.0
  path_provider: ^2.0.13
  get: ^4.6.5
  regexed_validator: ^2.0.0+1

dev_dependencies:
  freezed: ^2.3.2
  flutter_launcher_icons: ^0.12.0
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.1.0+1
  json_serializable: ^6.6.1

flutter_gen:
  integrations:
    flutter_svg: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
          weight: 500
